# templated from here: https://www.youtube.com/watch?v=EQNO_kM96Mo
# code here: https://gitlab.com/nanuchi/youtube-tutorial-series/-/blob/master/demo-kubernetes-components/mongo.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server-deployment
  labels:
    app: drone-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-server
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
      - name: drone-server
        image: anastasofpv/drone-server:13
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: drone-server-service
spec:
  selector:
    app: drone-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: drone-db
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: admin
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: drone-db
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-server-deployment
  labels:
    app: rtsp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtsp-server
  template:
    metadata:
      labels:
        app: rtsp-server
    spec:
      containers:
      - name: rtsp-server
        image: aler9/rtsp-simple-server
        ports:
        - containerPort: 8554
        - containerPort: 1935
        - containerPort: 8888
        env:
        - name: RTSP_PROTOCOLS
          value: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: rtsp-server-service
spec:
  selector:
    app: rtsp-server
  ports:
    - name: port1
      protocol: TCP
      port: 8554
      targetPort: 8554
    - name: port2
      protocol: TCP
      port: 1935
      targetPort: 1935
    - name: port3
      protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-ssh-tunnel-deployment
  labels:
    app: reverse-ssh-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-ssh-tunnel
  template:
    metadata:
      labels:
        app: reverse-ssh-tunnel
    spec:
      containers:
      - name: reverse-ssh-tunnel
        image: efrecon/rsshd
        ports:
        - containerPort: 22
        - containerPort: 3031
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-ssh-tunnel-service
spec:
  selector:
    app: reverse-ssh-tunnel
  ports:
    - name: port1
      protocol: TCP
      port: 22
      targetPort: 3029
    - name: port2
      protocol: TCP
      port: 3031
      targetPort: 3031